### ISSUE TITLE
Graphene usage with GraphQL-utitlities

### ISSUE THREAD

**Issue by vancouverwill** [melvinkcx/graphql-utilities#9]
Hey I saw your issue on Graphene as I was looking around for how to have request level middleware and evidently i'm not the only person who has had this issue :smile: https://github.com/graphql-python/graphene/issues/1117

Seems like your library solves that plus some other useful features but from the looks of https://github.com/melvinkcx/graphql-utilities/blob/a78299624356e53f2004bc56190642139b3f2ac3/setup.py#L42 it requires greater than `graphql-core` > 3 and latest stable version of `Graphene` requires `graphql-core` < 3 

https://github.com/graphql-python/graphene/blob/3d0e460be166cbb7c3701a9d91030eb15c73e382/setup.py#L88 

Just wondering if they were designed to work together or is this more of a replacement? Thanks and great work :+1:

**Comment by melvinkcx** [comment]
Thanks for showing interest.

Initially, this library was designed for the next version of Graphene which
uses graphql-core > 3, which is expected to be released soon.

Coincidentally,  the middleware decorator also works well with the current
stable version.

I'm not considering to remove the constraint of requiring graphql-core > 3
since the other features will only work with graphql-core > 3.

Any suggestions are welcome :)

**Comment by vancouverwill** [comment]
Okay thanks for explaining and for the hard work on this. Will wait to Graphene 3.x is stable and use the decorator as is for now. Potentially could help with issues if they come up but all looks under control for now.
